inherit_from:
  - .rubocop_todo.yml

AsciiComments:
  Enabled: false

Lambda:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

AccessorMethodName:
  Enabled: false

Documentation:
  Enabled: false

AndOr:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/environments/*

Lint/UselessAssignment:
  Exclude:
    - spec/**/*

AllCops:
  Exclude:
    - db/**/*
    - config/initializers/*
    - config/unicorn.rb
    - config/unicorn_staging.rb
    - tmp/**/*
    - node_modules/**/*
    - vendor/**/*
    - "bin/*"
