version: "3"
services:
  db:
    image: postgres:11.0-alpine
    volumes:
      - datavol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kagamirror
      POSTGRES_PASSWORD: secret
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  datavol:
