version: "3"
services:
  db:
    image: postgres:14.2
    volumes:
      - datavol:/var/lib/postgresql/data
    env_file: .env.test
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: test
    volumes:
      - .:/app
    env_file: .env.test
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  datavol:
