FROM ruby:2.6.3

ARG RAILS_ENV
ARG RAILS_MASTER_KEY

ENV RAILS_ENV ${RAILS_ENV}
ENV RAILS_MASTER_KEY ${RAILS_MASTER_KEY}

ENV APP_ROOT /app
RUN mkdir -p $APP_ROOT
WORKDIR $APP_ROOT

RUN echo "deb http://security.debian.org jessie/updates main" >> /etc/apt/sources.list &&\
	curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get update -qq \
	&& apt-get install -y build-essential libpq-dev nodejs postgresql-client

RUN apt-get update && apt-get install -y unzip && \
	CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE` && \
	wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/ && \
	unzip ~/chromedriver_linux64.zip -d ~/ && \
	rm ~/chromedriver_linux64.zip && \
	chown root:root ~/chromedriver && \
	chmod 755 ~/chromedriver && \
	mv ~/chromedriver /usr/bin/chromedriver && \
	sh -c 'wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -' && \
	sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' && \
	apt-get update && apt-get install -y google-chrome-stable

RUN apt-get install -y vim

COPY Gemfile $APP_ROOT/Gemfile
COPY Gemfile.lock $APP_ROOT/Gemfile.lock
RUN bundle install

COPY . $APP_ROOT

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
