version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: create db
          command: docker-compose run web rails db:create
      - run:
          name: create tables
          command: docker-compose run web bundle exec ridgepole --apply -f db/Schemafile -c config/database.yml
      - run:
          name: rubocop
          command: docker-compose run web bundle exec rubocop --auto-correct
      - run:
          name: rubocop-faker
          command: docker-compose run web bundle exec rubocop --require rubocop-faker --only Faker/DeprecatedArguments --auto-correct
      - run:
          name: test
          command: docker-compose run web bin/rspec
      - run:
          name: docker-compose down
          command: docker-compose down
